name: Generate PR (example)

on:
  issues:
    types:
      - labeled

jobs:
  generate-pr:
    runs-on: ubuntu-latest
    # Only run if the label name includes 'ai-pr' and an issue number is available
    if: contains(github.event.label.name, 'ai-pr') && github.event.issue.number != null
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install
      - name: Generate PR with AI
        uses: WillBooster/generate-pr-with-llm@v1
        with:
          # required options
          issue-number: ${{ github.event.issue.number }}
          # optional options
          planning-model: gemini-2.5-pro-preview-05-06
          reasoning-effort: high
          repomix-extra-args: "--compress --remove-empty-lines --include 'src/**/*.ts'"
          aider-extra-args: '--model gemini/gemini-2.5-pro-preview-05-06 --edit-format diff-fenced --chat-language English'
          test-command: 'yarn check-for-ai'
          max-test-attempts: 10
        env:
          # for Amazon (Bedrock)
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION_NAME: us-west-2
          # for Google (AI Studio)
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          # for OpenAI
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GH_TOKEN: ${{ secrets.PUBLIC_GH_BOT_PAT }}
